### DISCUSSION TITLE
You can throw your mouse away with this keyboard remapping| vim gang

### DISCUSSION THREAD

**Discussion by cutbypham** [sezanzeb/input-remapper#610] [Show and tell]
- Video demo: https://youtu.be/pKtIrQsbKnQ

- Hold `Tab` 
+ `h` `j` `k` `l` moving cursor `left` `down` `up` `right` (vim) || hold `tab + space` + hjkl speed is slow down
+ `w` button left, `e` button middle, `r` button right
+ `;` scroll down, `p` scroll up, `i` scroll left, `o` scroll right
> I use qwerty layout
- With this basic ideas you can use input remapper or the software you can think can do with action
- Input remapper config: https://github.com/thuanowa/dotfiles/blob/3e8b63c4f9020ed05b0c159ab901d2e82c421b55/input-remapper/presets/SEMICO%20%20%20USB%20Gaming%20Keyboard%20/thuan_fly_key.json

**Comment by cutbypham** [comment]
```json
{
    "mapping": {
        "1,57,1+1,22,1": [
            "KEY_PAGEUP",
            "keyboard"
        ],
        "1,57,1+1,25,1": [
            "KEY_PAGEDOWN",
            "keyboard"
        ],
        "1,127,1": [
            "KEY_LEFTCTRL",
            "keyboard"
        ],
        "1,57,1+1,35,1": [
            "KEY_LEFT",
            "keyboard"
        ],
        "1,57,1+1,36,1": [
            "KEY_DOWN",
            "keyboard"
        ],
        "1,57,1+1,38,1": [
            "KEY_RIGHT",
            "keyboard"
        ],
        "1,57,1+1,23,1": [
            "KEY_HOME",
            "keyboard"
        ],
        "1,57,1+1,24,1": [
            "KEY_END",
            "keyboard"
        ],
        "1,57,1+1,12,1": [
            "KEY_F11",
            "keyboard"
        ],
        "1,57,1+1,13,1": [
            "KEY_F12",
            "keyboard"
        ],
        "1,57,1+1,37,1": [
            "KEY_UP",
            "keyboard"
        ],
        "1,57,1+1,26,1": [
            "Alt_L+KEY_LEFT",
            "keyboard"
        ],
        "1,57,1+1,27,1": [
            "Alt_L+KEY_RIGHT",
            "keyboard"
        ],
        "1,57,1+1,3,1": [
            "KEY_F2",
            "keyboard"
        ],
        "1,57,1+1,4,1": [
            "KEY_F3",
            "keyboard"
        ],
        "1,57,1+1,5,1": [
            "KEY_F4",
            "keyboard"
        ],
        "1,57,1+1,6,1": [
            "KEY_F5",
            "keyboard"
        ],
        "1,57,1+1,7,1": [
            "KEY_F6",
            "keyboard"
        ],
        "1,57,1+1,8,1": [
            "KEY_F7",
            "keyboard"
        ],
        "1,57,1+1,10,1": [
            "KEY_F9",
            "keyboard"
        ],
        "1,57,1+1,9,1": [
            "KEY_F8",
            "keyboard"
        ],
        "1,57,1+1,11,1": [
            "KEY_F10",
            "keyboard"
        ],
        "1,57,1+1,39,1": [
            "KEY_RIGHTCTRL+a+f",
            "keyboard"
        ],
        "1,149,1": [
            "XF86RotateWindows",
            "keyboard"
        ],
        "1,58,1": [
            "Escape",
            "keyboard"
        ],
        "1,59,1": [
            "XF86AudioMute",
            "keyboard"
        ],
        "1,57,1+1,2,1": [
            "KEY_F1",
            "keyboard"
        ],
        "1,61,1": [
            "XF86AudioRaiseVolume",
            "keyboard"
        ],
        "1,60,1": [
            "XF86AudioLowerVolume",
            "keyboard"
        ],
        "1,63,1": [
            "XF86AudioMicMute",
            "keyboard"
        ],
        "1,64,1": [
            "XF86WebCam",
            "keyboard"
        ],
        "1,65,1": [
            "KEY_LEFTCTRL+c",
            "keyboard"
        ],
        "1,66,1": [
            "KEY_LEFTCTRL+Shift_L+v",
            "keyboard"
        ],
        "1,57,1+1,44,1": [
            "Alt_L+KEY_F10",
            "keyboard"
        ],
        "1,57,1+1,45,1": [
            "Alt_L+KEY_F4",
            "keyboard"
        ],
        "1,57,1+1,47,1": [
            "Super_L+Shift_L+v",
            "keyboard"
        ],
        "1,15,1+1,19,1": [
            "BTN_RIGHT",
            "mouse"
        ],
        "1,15,1+1,17,1": [
            "BTN_LEFT",
            "mouse"
        ],
        "1,57,1+1,52,1": [
            "Shift_L+Super_L+KEY_RIGHT",
            "keyboard"
        ],
        "1,57,1+1,51,1": [
            "Shift_L+Super_L+KEY_LEFT",
            "keyboard"
        ],
        "1,86,1": [
            "KEY_LEFTCTRL",
            "keyboard"
        ],
        "1,15,1+1,57,1+1,38,1": [
            "mouse(right, 2)",
            "mouse"
        ],
        "1,57,1+1,15,1+1,36,1": [
            "mouse(down, 2)",
            "mouse"
        ],
        "1,57,1+1,15,1+1,37,1": [
            "mouse(up,2)",
            "mouse"
        ],
        "1,57,1+1,15,1+1,35,1": [
            "mouse(left,2)",
            "mouse"
        ],
        "1,15,1+1,25,1": [
            "wheel(up, 20)",
            "mouse"
        ],
        "1,15,1+1,24,1": [
            "wheel(left,20)",
            "mouse"
        ],
        "1,15,1+1,23,1": [
            "wheel(right,20)",
            "mouse"
        ],
        "1,15,1+1,39,1": [
            "wheel(down,20)",
            "mouse"
        ],
        "1,15,1+1,35,1": [
            "mouse(left,8)",
            "mouse"
        ],
        "1,15,1+1,37,1": [
            "mouse(up,8)",
            "mouse"
        ],
        "1,15,1+1,36,1": [
            "mouse(down,8)",
            "mouse"
        ],
        "1,15,1+1,38,1": [
            "mouse(right,8)",
            "mouse"
        ],
        "1,15,1+1,18,1": [
            "BTN_MIDDLE",
            "mouse"
        ],
        "1,67,1": [
            "KEY_LEFTCTRL+XF86MonBrightnessDown",
            "keyboard"
        ],
        "1,68,1": [
            "KEY_LEFTCTRL+XF86MonBrightnessUp",
            "keyboard"
        ],
        "1,15,1": [
            "if_single(key(KEY_TAB), ,10000)",
            "keyboard"
        ],
        "1,57,1": [
            "if_single(key(KEY_SPACE),,10000)",
            "keyboard"
        ],
        "1,57,1+1,30,1": [
            "Super_L+1+Super_L+h",
            "keyboard"
        ],
        "1,57,1+1,31,1": [
            "Super_L+2+Super_L+h",
            "keyboard"
        ],
        "1,57,1+1,32,1": [
            "Super_L+3+Super_L+h",
            "keyboard"
        ],
        "1,57,1+1,33,1": [
            "Super_L+4+Super_L+h",
            "keyboard"
        ],
        "1,57,1+1,16,1": [
            "Super_L+6+Super_L+h",
            "keyboard"
        ],
        "1,57,1+1,34,1": [
            "Super_L+5+Super_L+h",
            "keyboard"
        ],
        "1,57,1+1,17,1": [
            "Super_L+7+Super_L+h",
            "keyboard"
        ],
        "1,57,1+1,18,1": [
            "Super_L+8+Super_L+h",
            "keyboard"
        ],
        "1,57,1+1,19,1": [
            "Super_L+9+Super_L+h",
            "keyboard"
        ],
        "1,57,1+1,20,1": [
            "Super_L+0+Super_L+h",
            "keyboard"
        ]
    }
}
```

**Comment by cutbypham** [comment]
with version >= 1.5.1, kinda broken

**Reply by cutbypham** [reply]
fix with `mouseless`: https://github.com/jbensmann/mouseless
mouseless config: https://github.com/jbensmann/mouseless/issues/25#issuecomment-1505287729

**Comment by trapexit** [comment]
Can this be done by using a second input device as a Fn key of sorts? I have a Thinkpad with a physical middle mouse button and would like to replicate the layering system I have with my TEX Shinobi (where the middle mouse button is also a Fn key).

**Reply by cutbypham** [reply]
I'm not quite sure, you can try to debug mode to see.

![image](https://user-images.githubusercontent.com/40050527/232827409-993b6d0e-a4e4-4641-8cce-14c8cdea3146.png)

> https://github.com/jbensmann/mouseless/pull/24

```bash
make install
make debug
```

latest config
```yaml
# the keyboard devices it reads from, if no devices are specified, it reads from all
devices:
# - "/dev/input/by-id/SOME_KEYBOARD_REPLACE_ME-event-kbd"

# startCommand: "setxkbmap de"

baseMouseSpeed: 750.0
baseScrollSpeed: 20.0

mouseAccelerationTime: 200.0
mouseAccelerationCurve: 2.0

startMouseSpeed: 0.0

mouseDecelerationTime: 300.0
mouseDecelerationCurve: 3.0

layers:
  - name: initial
    bindings:
      a: tap-hold a ; toggle-layer mouse ; 300
      space: tap-hold space ; toggle-layer thuan_fly_keys ; 200
      s: tap-hold s ; toggle-layer uwu ; 300

      # capslock kinda useless for me, so i map it to esc for vim
      capslock: esc

      # key `|\` at the bottom on msi laptop keyboard, why? they put the key in this position
      102nd: leftctrl

      #####################
      # External keyboard #
      #####################

      # key menu
      compose: leftctrl
      f1: mute
      f2: volumedown
      f3: volumeup
      # mic mute, `KEY_MICMUTE` ~ micmute doesn't work, debug show key press is `f20`
      f5: f20

  - name: mouse
    passThrough: false
    bindings:
      a: layer initial
      i: layer mouse
      r: reload-config
      l: move  1  0
      h: move -1  0
      j: move  0  1
      k: move  0 -1
      p: scroll up
      semicolon: scroll down
      leftalt: speed 4.0
      space: speed 0.3
      f: button left
      d: button middle
      s: button right

  - name: thuan_fly_keys
    passThrough: true
    bindings:
      # function key kinda far, lazy to reach out
      k1: f1
      k2: f2
      k3: f3
      k4: f4
      k5: f5
      k6: f6
      k7: f7
      k8: f8
      k9: f9
      k0: f10
      minus: f11
      equal: f12

      ##################
      ## editing text ##
      ##################

      k: up
      h: left
      j: down
      l: right
      i: home
      o: end

      ###########
      ## Gnome ##
      ###########

      # switch to fav app on dash
      a: leftmeta+k1
      s: leftmeta+k2
      d: leftmeta+k3
      f: leftmeta+k4
      g: leftmeta+k5
      q: leftmeta+k6
      w: leftmeta+k7
      e: leftmeta+k8
      r: leftmeta+k9

      # resize windows
      c: rightalt+f8

      # pano clipboard extension
      v: leftmeta+leftshift+v

      # switch windows to monitor left
      comma: leftmeta+leftshift+left

      # switch windows to monitor right
      dot: leftmeta+leftshift+right

      # toggle maximize
      m: leftalt+f10

      # close window
      x: leftalt+f4

      #############
      ## browser ##
      #############

      # restore tab
      t: leftctrl+leftshift+t

      # next tab aka `ctrl + tab`
      p: leftctrl+pagedown

      # previous tab aka `ctrl + shift + tab`
      u: leftctrl+pageup

      # go back
      leftbrace: leftalt+left

      # go forward
      rightbrace: leftalt+right

  - name: uwu
    passThrough: false
    bindings:
      s: layer initial
      i: layer uwu
      j: pagedown
      k: pageup
      h: left
      l: right
```

**Reply by trapexit** [reply]
Perhaps I'm misunderstanding what you're describing but what I'm looking for is not to control a mouse with the keyboard but kinda the reverse. On the TEX Shinobi keyboard you can use the middle mouse button as a Fn key and I use that to issue key presses that would require moving away from the home row such as mapping h, j, k, l to arrow keys when middle mouse button is held down. ie: MiddleMouseButton + h = left

**Reply by cutbypham** [reply]
I can remap `a` held down switch to layer `hjkl` to arrow keys while a single key press keeps the `a` function.

https://program.tex.com.tw/shinobi/#keymap

**Reply by cutbypham** [reply]
the example I map `s` when held down switch to layer 
```yaml
layers:
  - name: initial
    bindings:
      s: tap-hold s ; toggle-layer uwu ; 300

  - name: uwu
    passThrough: false
    bindings:
      s: layer initial
      i: layer uwu
      j: pagedown
      k: pageup
      h: left
      l: right
```
